### PR TITLE
Website Chinese Translation & Prettier

### PR DESCRIPTION
**Pull request by Edit-Mr**
**Summary:**
This pull request includes the following changes:
1. **Added Translation Package**: Integrated a new translation package [eleventy-plugin-i18n](https://github.com/adamduncan/eleventy-plugin-i18n) to support multiple languages.
2. **UI Changes**: The user interface was updated to include a language selection option and be responsive. The CSS font `system-ui` was added to avoid a bad font in Chinese by default.
3. **Translated to Traditional Chinese**: All text including example slide are translated.
4. **Add Redirect**: Set default language to English.
5. **Add Format Rule**: Add Prettier to format code (ignore markdown) and use GitHub Action to Automatically check the code.
6. **Document**: Update document including formatting rules and translation guide.

**Preview:**
This is what it looks like currently. You can preview it [here](https://deploy-preview-63--revealjs.netlify.app/).

圖片

**To-Do**:
All things are done.

**Notes**:
- Feedback and suggestions are welcome!

### CODE REVIEW

**Comment by hakimel** [comment]
This is a great contribution—thanks @Edit-Mr!

Looks like you saved some existing files with a code formatter which ended up causing unexpected changes. I know there's no code formatter configured for this project (todo for me) but I want to stick to single quotes and use 2-space indentation. Could you please undo the double-quote and indentation changes in `main.js`, `home.js`, `css/*.scss`, and `package.json`? Thanks.

**Comment by Edit-Mr** [comment]
Hi @hakimel,

Thanks for your reply. I can add Prettier to the project. What do you think?

**Comment by hakimel** [comment]
Would be much appreciated, thanks! I normally use:
```
{
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "singleQuote": true
}
```

**Comment by Edit-Mr** [comment]
Done. Let me rewrite the README and do some check real quick (:

**Comment by hakimel** [comment]
Sorry to be a pain, but can we make prettier ignore all of the content (.md) files? There are a lot of code samples in those files which have been manually formatted for readability and fitting on fewer lines.

**Comment by Edit-Mr** [comment]
Ah, I see 🤣 no problem.

**Comment by Edit-Mr** [comment]
@hakimel Everything should be done now, I think.

**Comment by Edit-Mr** [comment]
@hakimel Everything should be done now.

**Comment by hakimel** [comment]
I've been testing this but noticed two issues;

1
The language switcher should switch languages without changing to a different page. Right now, clicking English leads to a 404 page and picking Chinese always goes back to the landing page.

2
When starting the dev server, a few 100 warnings are shown about strings not being found. It seems like it might be looking for strings in the wrong place but I'm not sure. Here are a few example logs:
```
[i18n] Could not find 'Installation' in 'upgrading'. Using 'en' fallback.
[i18n] Could not find 'Support' in 'upgrading'. Using 'en' fallback.
[i18n] Could not find 'Video Course' in 'upgrading'. Using 'en' fallback.
[i18n] Could not find 'Sponsor' in 'upgrading'. Using 'en' fallback.
...
[i18n] Could not find 'Using Plugins' in ''. Using 'en' fallback.
[i18n] Could not find 'Built-in Plugins' in ''. Using 'en' fallback.
[i18n] Could not find 'Creating a Plugin' in ''. Using 'en' fallback.
[i18n] Could not find 'Multiplex' in ''. Using 'en' fallback.
```

Do you think you can address those @Edit-Mr? Let me know if I can help.

**Comment by Edit-Mr** [comment]
@hakimel  You're right. Changing the language will direct to home page. I can change it if you like to.
The reason English pages seems to be 404 is because I've set up redirect rule that English will be the default language. So /en would be redirect to /. (It works on the preview link generated by Netlify.) 
This is the reason why you saw the warning, you can see it the console text is yellow instead of red, it's just a friendly remind that you are using default language - English.
However it only works on Netlify deployment. To run it locally, you'll need to run Netlify CLI.

**Comment by Edit-Mr** [comment]
@hakimel Done.

**Comment by hakimel** [comment]
Looks great! Thank you so much for all your work on this 🙌

**Pull request merged**
