### PR TITLE
Add 'React Framework' page to 'Other' section

### PR DESCRIPTION
**Pull request by bouzidanas**
Added page to Other section with instructions and information on how to incorporate Reveal.js into React projects (with a focus on Vite project setups). The decision to focus on Vite is because everything was tested in a Vite project environment. I authored a React + Reveal.js package and this package was created and setup with Vite. So in the interest of reproducibility and avoiding bugs due to variations in project setups, I chose to focus on Vite + React project setups. 

However, the information and solutions provided should be helpful for incorporating Reveal.js into any React project. Especially, the "Programmatic" subsection. I also included a brief section on 3rd party packages/tools at the end.

The creation of this page was motivated by a suggestion made by @hakimel in the discourse of an open issue (https://github.com/hakimel/reveal.js/issues/3152#issuecomment-1722170876)

### Relevant issues:
- https://github.com/hakimel/reveal.js/issues/3152#issue-1162577898
- https://github.com/hakimel/reveal.js/issues/3466
- https://github.com/hakimel/reveal.js/issues/2925
- https://github.com/hakimel/reveal.js/issues/2155

### CODE REVIEW

**Comment by hakimel** [comment]
Adding a guide for using reveal.js in react is a great idea @bouzidanas, thanks! I've been meaning to write an official reveal-react wrapper but haven't found the time yet 😅

A little feedback on the "full" react example at the end of the article. Instead of using the DOM to avoid double initialization in strict mode, I think it's better to check if the ref is already set. I also found a few smaller syntax errors. Here's a revised example that I've confirmed to be working in a fresh vite install;

```tsx
import { useEffect, useRef } from "react";
import Reveal from "reveal.js";
import "reveal.js/dist/reveal.css";
import "reveal.js/dist/theme/black.css";

function App() {
    const deckDivRef = useRef<HTMLDivElement>(null) // keep reference to deck container div
    const deckRef = useRef<Reveal.Api|null>(null); // keep reference to deck reveal instance

    useEffect(() => {
        // Prevents double initialization in strict mode
        if (deckRef.current) return;

        deckRef.current = new Reveal(deckDivRef.current!, {
            transition: "slide",
            // other config options
        });

        deckRef.current.initialize().then(() => {
            // good place for event handlers and plugin setups
        });

        return () => {
            try {
                if (deckRef.current) {
                    deckRef.current.destroy();
                    deckRef.current = null;
                }
            } catch (e) {
                console.warn("Reveal.js destroy call failed.");
            }
        };
    }, []);

    return (
        // Your presentation is sized based on the width and height of
        // our parent element. Make sure the parent is not 0-height.
        <div className="reveal" ref={deckDivRef}>
            <div className="slides">
                <section>Slide 1</section>
                <section>Slide 2</section>
            </div>
        </div>
    );
}

export default App;
```

**Comment by bouzidanas** [comment]
> Adding a guide for using reveal.js in react is a great idea @bouzidanas, thanks! I've been meaning to write an official reveal-react wrapper but haven't found the time yet 😅

It was sorta your idea to begin with 😄and I understand.

>I think it's better to check if the ref is already set.

I was going to respond with that I tried this already and it doesnt work for me until I tried it again and it worked! Super strange! I will also have to check that this works in the package I built to see if anything else is causing the issue. I might have been using the other ref by accident or something...🤷‍♂️

I also prefer the idea of multipurpose-ing that ref and using it as an initialization flag.

Also, it is worth discussing imo whether or not to go with typescript or javascript for the code. I was thinking on that and I came to the conclusion that it is more consistent with the rest of the docs to go with javascript but more helpful to go with typescript (since typescript is pretty much the industry standard in React world).

For now, I will incorporate your suggestions and change the code at the end of the guide to be:

```ts
import { useEffect, useRef } from "react";
import Reveal from "reveal.js";
import "reveal.js/dist/reveal.css";
import "reveal.js/dist/theme/black.css";

function App() {
    const deckDivRef = useRef<HTMLDivElement>(null) // keep reference to deck container div
    const deckRef = useRef<Reveal.Api | null>(null); // keep reference to deck reveal instance

    useEffect(() => {
        // Prevents double initialization in strict mode
        if (deckRef.current) return;

        deckRef.current = new Reveal(deckDivRef.current!, {
            transition: "slide",
            // other config options
        });

        deckRef.current.initialize().then(() => {
            // good place for event handlers and plugin setups
        });

        return () => {
            try {
                if (deckRef.current) {
                    deckRef.current.destroy();
                    deckRef.current = null;
                }
            } catch (e) {
                console.warn("Reveal.js destroy call failed.");
            }
        };
    }, []);

    return (
        // Your presentation is sized based on the width and height of
        // our parent element. Make sure the parent is not 0-height.
        <div className="reveal" ref={deckDivRef}>
            <div className="slides">
                <section>Slide 1</section>
                <section>Slide 2</section>
            </div>
        </div>
    );
}

export default App;
```

**Comment by bouzidanas** [comment]
Oh also I forgot to mention that the "wrapper" (although it feels more like Reveal wrapping React 😂) that I built incorporates pretty much everything in that last example with a bunch more things added to allow for changing deck 'state', content, theme, , configuration and more. I mention this now because it is opensource! So feel free to take a look and use use what you like as a starting point for an official React wrapper! 

- [react-reveal-slides](https://github.com/bouzidanas/react-reveal-slides)

I think its getting close to being production ready.

**Comment by hakimel** [comment]
This is live at https://revealjs.com/react/ now. Thanks for the contribution!

Reading the article again it felt confusing to suggest two different but similar approaches to get reveal.js into react. I think it's better to suggest the on approach we thinks is best. That said I dropped the part that suggested adding the reveal markup inside of index.html in favor of the recommended approach where everything is moved into react.

Hope that makes sense—if there's a compelling reason for the other form of rendering I'm open to bringing that content back.

**Comment by bouzidanas** [comment]
I understand. The motivation for the write up on the manual approach was due to the issues I saw related to react and reveal.js.

I think the islands idea using react portals (like ASTRO islands) is potentially interesting to some people who just want to embed a couple react components into the presentation rather have the presentation inside the react app. I think one issue was posted requesting something like this.

However, looking back at the page, I do agree that there is a bit too much to absorb and I might have overcomplicated things. First off, I should've started with the recommended approach and left the manual approach (of altering the html document) to later. Secondly, by devoting a larger portion of the article to the manual approach, I take the focus and attention away from the simpler and, in my opinion, the preferred approach ie the recommended one.

All in all, I don't see any major problems with your decision.

**Comment by bouzidanas** [comment]
Looking at the page in full, there is something that I think doesnt make much sense now that the Manual subsection is removed. 
I dont think it makes much sense to highlight the first enumerated list item as recommended. It kinda gives the sense that using 3rd party tools is advised against which I believe is not intended. 

So basically change

```markdown
Reveal.js can be added to a React project a few different ways.

1. [Install and setup reveal.js via npm](https://revealjs.com/react/#installing-from-npm) (recommended)
2. [Use third-party packages](https://revealjs.com/react/#third-party-packages)
```

to 

```markdown
Reveal.js can be added to a React project a few different ways.

1. [Install and setup reveal.js via npm](https://revealjs.com/react/#installing-from-npm)
2. [Use third-party packages](https://revealjs.com/react/#third-party-packages)
```

I can make another pull request if you want but I dont currently see the need for the overhead for something so small.

**Comment by bouzidanas** [comment]
@hakimel , 
Looking at the page in full, there is something that I think doesnt make much sense now that the Manual subsection is removed. 
I dont think it makes much sense to highlight the first enumerated list item as recommended. It kinda gives the sense that using 3rd party tools is advised against which I believe is not intended. 

So basically change

```markdown
Reveal.js can be added to a React project a few different ways.

1. [Install and setup reveal.js via npm](https://revealjs.com/react/#installing-from-npm) (recommended)
2. [Use third-party packages](https://revealjs.com/react/#third-party-packages)
```

to 

```markdown
Reveal.js can be added to a React project a few different ways.

1. [Install and setup reveal.js via npm](https://revealjs.com/react/#installing-from-npm)
2. [Use third-party packages](https://revealjs.com/react/#third-party-packages)
```

I can make another pull request if you want but I dont currently see the need for the overhead for something so small.

**Comment by hakimel** [comment]
Good point—addressed in ef076154ed5162354833f89b6f5489c157aed05b

**Pull request merged**
