### PR TITLE
fix: update MathJax URL to 2.7.8

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by pkra** [comment]
v2.7.0 is 4 years old. See also https://www.mathjax.org/MathJax-v2-7-8-available/

**Comment by hakimel** [comment]
Thanks. 

We're switching to KaTeX as our built-in math typesetting plugin in 4.1 so this will be updated again when that happens. The current MathJax-based math plugin will remain available in a separate repo though.

**Comment by pkra** [comment]
> We're switching to KaTeX as our built-in math typesetting plugin in 4.1 

FYI that change will break a lot of content. MathJax v3 might be worth a look.

**Comment by hakimel** [comment]
I don't use math typesetting myself so I've been looking for more info about that from others. From what I've heard, the features they support seem comparable. Is there anything in particular that's not available in KaTeX which would cause breaking changes?

**Pull request merged**
